name: Python CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install dependencies
      run: |
        pip install flake8 pytest pylint black isort
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Check Black formatting
      run: find . -name "*.py" -exec black {} +

    - name: Lint with Pylint
      run: find . -name "*.py" -exec pylint {} +

    - name: Run Pytest
      run: pytest

    - name: Sort imports with isort
      run: find . -name "*.py" -exec isort {} +
